//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvidencijaVremena
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evidencija
    {
        public int ID { get; set; }
        public int Trajanje { get; set; }
        public System.DateTime DatumUnosa { get; set; }
        public int KorisnikID { get; set; }
        public int AktivnostID { get; set; }
    
        public virtual Aktivnost Aktivnost { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
