//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvidencijaVremena
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opterecenje
    {
        public int ID { get; set; }
        public int PredmetID { get; set; }
        public int TipAktivnostiID { get; set; }
        public Nullable<int> Iznos { get; set; }
    
        public virtual Predmet Predmet { get; set; }
        public virtual TipAktivnosti TipAktivnosti { get; set; }
    }
}
