-- Vedran Biđin, 11.4.2016.
-- Završni rad - baza podataka

CREATE TABLE University
(
	ID INT PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL UNIQUE,
	Acronym NVARCHAR(10),
);
	
CREATE TABLE College
(
	ID INT PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Acronym NVARCHAR(10),
	UniversityID INT FOREIGN KEY REFERENCES University(ID),
	CONSTRAINT College_UQ UNIQUE (Name, UniversityID)
);

CREATE TABLE Subject
(
	ID INT PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL UNIQUE,
	ECTS INT CHECK (ECTS BETWEEN 0 and 180),
	CollegeID INT FOREIGN KEY REFERENCES College(ID),
	CONSTRAINT Subject_UQ UNIQUE (Name, CollegeID)
);

CREATE TABLE ActivityType
(
	ID INT PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL UNIQUE,
);

CREATE TABLE Activity
(
	ID INT PRIMARY KEY,
	SubjectID INT NOT NULL FOREIGN KEY REFERENCES Subject(ID),
	ActivityTypeID INT NOT NULL FOREIGN KEY REFERENCES ActivityType(ID),
	CONSTRAINT Activity_UQ UNIQUE (SubjectID, ActivityTypeID)
);

CREATE TABLE Account
(
	ID INT PRIMARY KEY,
	Username NVARCHAR(100) NOT NULL UNIQUE,
	PasswordHash BINARY(64) NOT NULL,
	Email NVARCHAR(100) NOT NULL UNIQUE,
	Role INT NOT NULL CHECK (Role BETWEEN 0 and 2)
);

CREATE TABLE Subscription
(
	ID INT PRIMARY KEY,
	AccountID INT NOT NULL FOREIGN KEY REFERENCES Account(ID),
	SubjectID INT NOT NULL FOREIGN KEY REFERENCES Subject(ID),
	CONSTRAINT Subscription_UQ UNIQUE (AccountID, SubjectID)
);

CREATE TABLE Entry
(
	ID INT PRIMARY KEY,
	Seconds INT NOT NULL,
	EntryDate DATETIME NOT NULL,
	AccountID INT FOREIGN KEY REFERENCES Account(ID),
	ActivityID INT FOREIGN KEY REFERENCES Activity(ID)
);
